"""Initial migration

Revision ID: a40df732af47
Revises: 
Create Date: 2024-10-17 15:46:51.472337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40df732af47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population',
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('country', name='population_pkey')
    )
    # ### end Alembic commands ###
